services:
  web:
    container_name: mlcbakery
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mlcbakery
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - caddy-network

  streamlit:
    container_name: mlcbakery_streamlit
    build: .
    command: streamlit run mlcbakery/webclient/dataset_viewer.py --server.port 8000 --server.address 0.0.0.0
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mlcbakery
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - caddy-network

  db:
    image: postgres:16-alpine
    container_name: mlcbakery_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlcbakery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - caddy-network

  caddy:
    image: caddy:2.9.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - streamlit
    networks:
      - caddy-network
volumes:
  caddy_data:
  caddy_config:
  postgres_data:

networks:
  caddy-network:
    external: true