include:
  - docker-compose.yml

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: mlcbakery_otel_collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      db:
        condition: service_started