include:
  - docker-compose.yml

streamlit:
  container_name: mlcbakery_streamlit
  build: .
  command: streamlit run mlcbakery/webclient/dataset_viewer.py --server.port 8000 --server.address 0.0.0.0
  volumes:
    - .:/app
  environment:
    - PYTHONPATH=/app
    - MLCBAKERY_API_BASE_URL=${MLCBAKERY_API_BASE_URL}


