services:
  api:
    container_name: mlcbakery
    build:
      context: .
      dockerfile: Dockerfile.bakery
    ports:
      - "8000:8000"
    volumes:
      - .:/app    
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app
      - ADMIN_AUTH_TOKEN=${ADMIN_AUTH_TOKEN}
    depends_on:
      - db

  mcp:
    container_name: mcp
    build:
      context: .
      dockerfile: Dockerfile.mcp
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MLCBAKERY_API_BASE_URL=${MLCBAKERY_API_BASE_URL}


  db:
    image: postgres:16-alpine
    container_name: mlcbakery_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlcbakery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  caddy:
    image: caddy:2.10.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  search:
    image: typesense/typesense:0.25.2 # Use a specific version
    container_name: mlcbakery_typesense
    environment:
      - TYPESENSE_DATA_DIR=/data
      # Use a strong, randomly generated API key in production
      - TYPESENSE_API_KEY=thisisatestkey
      - TYPESENSE_ENABLE_CORS=true # Allow CORS for easier development
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108" # Default Typesense port

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  typesense_data: {} # Add volume definition
