services:
  api:
    container_name: mlcbakery
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    user: "${UID}:${GID}"
    
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - caddy-network

  mcp_server:
    container_name: mcp_server
    # use Dockerfile.mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp

    volumes:
      - .:/app
    user: "${UID}:${GID}"
    environment:
      - MLCBAKERY_API_BASE_URL=http://bakery.jetty.io
      - MLCBAKERY_HOST=https://bakery.jetty.io/api/v1
      - PYTHONPATH=/app
    command: ["python", "mcp_server/main.py", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - caddy-network

  streamlit:
    container_name: mlcbakery_streamlit
    build: .
    command: streamlit run mlcbakery/webclient/dataset_viewer.py --server.port 8000 --server.address 0.0.0.0
    volumes:
      - .:/app
    user: "${UID}:${GID}"
    environment:
      - PYTHONPATH=/app
      - MLCBAKERY_API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - caddy-network

  db:
    image: postgres:16-alpine
    container_name: mlcbakery_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlcbakery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - caddy-network

  caddy:
    image: caddy:2.10.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-network

  search:
    image: typesense/typesense:0.25.2 # Use a specific version
    container_name: mlcbakery_typesense
    environment:
      - TYPESENSE_DATA_DIR=/data
      # Use a strong, randomly generated API key in production
      - TYPESENSE_API_KEY=thisisatestkey
      - TYPESENSE_ENABLE_CORS=true # Allow CORS for easier development
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108" # Default Typesense port
    networks:
      - caddy-network

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  typesense_data: {} # Add volume definition

networks:
  caddy-network:
    external: true