"""make_activity_name_nullable_in_entity_relationships

Revision ID: 5f64b76e30ce
Revises: fe0cf3d69b11
Create Date: 2024-06-01 15:00:12.345678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func # Added for server_default


# revision identifiers, used by Alembic.
revision: str = '5f64b76e30ce'
down_revision: Union[str, None] = 'fe0cf3d69b11' # Set this to the previous migration ID if applicable
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_relationships', 'activity_id')
    op.drop_table('activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entity_relationships', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key('entity_relationships_activity_id_fkey', 'entity_relationships', 'activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###
