"""Add owner to collections

Revision ID: e44c37f17887
Revises: 5a6b7765ddca
Create Date: 2025-07-04 08:04:40.882039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44c37f17887'
down_revision: Union[str, None] = '5a6b7765ddca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("collections", sa.Column("owner_identifier", sa.String()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entities", "owner_identifier")
