name: Build and Deploy MCP Server to Cloud Run

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering from the Actions tab

env:
  # Define the image name you want to use locally during the build
  IMAGE_NAME: mlcbakery-unified
  GHCR_REGISTRY: ghcr.io
  # Derive GHCR image path from repo owner
  GHCR_IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/mlcbakery-unified

  # --- GCP & Cloud Run Details (Reference Secrets) ---
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  MCP_SERVICE_NAME: ${{ secrets.MCP_SERVER_SERVICE_NAME || 'mcp-server' }} # Default to mcp-server if secret not set

jobs:
  build_push_deploy:
    name: Build, Push and Deploy MCP Server
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Read repository content
      packages: write     # Push packages (Docker images) to GHCR
      id-token: write   # Obtain OIDC token for Google Cloud authentication

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GHCR
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
        service_account: ${{ env.GCP_SA_EMAIL }}

    - name: Create Cloud Run metadata file
      id: create-metadata
      run: |
        cat <<EOF > service.yaml
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: ${{ env.MCP_SERVICE_NAME }}
        spec:
          template:
            spec:
              containers:
              - image: ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }}
                command:
                - "python"
                args:
                - "mcp_server/main.py"
                - "--host"
                - "0.0.0.0"
                - "--port"
                - "8080"
        EOF
        echo "Created service.yaml"

    - name: Deploy MCP Server to Cloud Run
      id: deploy-mcp
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.MCP_SERVICE_NAME }}
        region: ${{ env.CLOUD_RUN_REGION }}
        image: ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }}
        # Reference the created metadata file
        metadata: ./service.yaml
        # Add flag to allow pulling public images
        flags: "--allow-unauthenticated"
        # Define environment variables for the Cloud Run service
        env_vars: |
          PYTHONPATH=/app
          MLCBAKERY_API_BASE_URL=${{ secrets.API_SERVICE_URL }}
          MLCBAKERY_HOST=${{ secrets.MLCBAKERY_HOST }}
          # Add other necessary env vars here

    - name: Output Cloud Run Service URL
      run: echo "MCP Server Deployed - ${{ steps.deploy-mcp.outputs.url }}"