name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering from the Actions tab

env:
  # Define the image name you want to use locally during the build
  IMAGE_NAME: mlcbakery-unified

jobs:
  build_and_push: # Renamed job for clarity
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      packages: write # Needed to push Docker image to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # User/org running the action
        password: ${{ secrets.GITHUB_TOKEN }} # Automatic token

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true # Push the image
        tags: | # Tags for GHCR
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
        # load: true # Removed load: true as it's not needed when pushing
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Push completed
      run: echo "Docker image ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }} pushed successfully." 