name: Build and Deploy MCP Server to Cloud Run

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering from the Actions tab

env:
  # Define the image name you want to use
  IMAGE_NAME: mlcbakery-mcp
  # Use GHCR path - derived from repository owner and image name
  GHCR_MCP_IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/mlcbakery-mcp
  GHCR_BAKERY_IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/mlcbakery-bakery

jobs:
  build_push_deploy:
    name: Build, Push to GHCR and Deploy MCP Server
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Read repository content
      packages: write     # Write access to GHCR
      id-token: write   # For GCP auth

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Authenticate to Google Cloud FIRST (needed for Cloud Run deployment)
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
        service_account: ${{ env.GCP_SA_EMAIL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

    # Build and push Docker image to GHCR
    - name: Build and push MCP Docker image to GHCR
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.mcp
        push: true
        tags: |
          ${{ env.GHCR_MCP_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_MCP_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

- name: Build and push Bakery Docker image to GHCR
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.bakery
        push: true
        tags: |
          ${{ env.GHCR_BAKERY_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_BAKERY_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
