name: Build and Deploy MCP Server to Cloud Run

on:
  push:
    branches: [ main ] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering from the Actions tab

env:
  # Use GHCR path - derived from repository owner and image name
  GHCR_IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/mlcbakery-mcp
  GHCR_BAKERY_IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/mlcbakery-bakery
  # --- GCP & Cloud Run Details (Reference Secrets) ---
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  MCP_SERVICE_NAME: ${{ secrets.MCP_SERVER_SERVICE_NAME || 'mcp-server' }} # Default to mcp-server if secret not set

jobs:
  build_push_deploy:
    name: Build, Push to GHCR and Deploy MCP Server
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Read repository content
      packages: write     # Write access to GHCR
      id-token: write   # For GCP auth

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Authenticate to Google Cloud FIRST (needed for Cloud Run deployment)
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
        service_account: ${{ env.GCP_SA_EMAIL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

    # Build and push Docker image to GHCR
    - name: Build and push Docker image to GHCR
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.mcp
        push: true
        tags: |
          ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Log in to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CLOUD_RUN_REGION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    # - name: Mirror GHCR image to Artifact Registry
    #   run: |
    #     docker pull ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }}
    #     docker tag ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }} ${{ env.GAR_IMAGE_PATH }}:${{ github.sha }}
    #     docker tag ${{ env.GHCR_IMAGE_PATH }}:${{ github.sha }} ${{ env.GAR_IMAGE_PATH }}:latest
    #     docker push ${{ env.GAR_IMAGE_PATH }}:${{ github.sha }}
    #     docker push ${{ env.GAR_IMAGE_PATH }}:latest


    # - name: Deploy MCP Server to Cloud Run
    #   id: deploy-mcp
    #   uses: google-github-actions/deploy-cloudrun@v2
    #   with:
    #     image: ${{ env.GAR_IMAGE_PATH }}:${{ github.sha }}
    #     service: ${{ env.MCP_SERVICE_NAME }}
    #     region: ${{ env.CLOUD_RUN_REGION }}
    #     # Ensure the Cloud Run service account has permissions to pull from GHCR if it's private
    #     # or configure the service for unauthenticated access if the GHCR package is public.
    #     # For public GHCR packages, you might need to configure Cloud Run to allow unauthenticated pulls
    #     # depending on your GCP organization policies.
    #     env_vars: |
    #       PYTHONPATH=/app
    #       MLCBAKERY_API_BASE_URL=${{ secrets.API_SERVICE_URL }}
    #       MLCBAKERY_HOST=${{ secrets.MLCBAKERY_HOST }}
    #       # Add other necessary env vars here
    # Build and push Docker image to GHCR
    - name: Build and push MCP Docker image to GHCR
      id: build-push-mcp
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.mcp
        push: true
        tags: |
          ${{ env.GHCR_MCP_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_MCP_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push Bakery Docker image to GHCR
      id: build-push-bakery
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.bakery
        push: true
        tags: |
          ${{ env.GHCR_BAKERY_IMAGE_PATH }}:${{ github.sha }}
          ${{ env.GHCR_BAKERY_IMAGE_PATH }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output Cloud Run Service URL
      run: echo "Successfully built and pushed image to GHCR"