name: Create Release Tag

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow a GHA to push to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Get version
        id: get_version
        run: |
          # Extracts version from [project] table, handles optional quotes and whitespace
          version=$(grep -E '^version\s*=\s*"?[0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]+)?(\.post[0-9]+)?(\.rc[0-9]+)?(\.alpha[0-9]+)?(\.beta[0-9]+)?"?' pyproject.toml | awk -F ' *= *' '{print $2}' | tr -d '\"')
          echo "Version: $version"
          echo "version_tag=v$version" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "${{ steps.get_version.outputs.version_tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.get_version.outputs.version_tag }} already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${{ steps.get_version.outputs.version_tag }} does not exist. Proceeding to create it."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git tag ${{ steps.get_version.outputs.version_tag }}
          git push origin ${{ steps.get_version.outputs.version_tag }}
          echo "Tag ${{ steps.get_version.outputs.version_tag }} created and pushed."
        shell: bash 