name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Verify sqlalchemy installation
      run: uv pip list | grep sqlalchemy || echo "SQLAlchemy not found"

    - name: Run tests
      env:
        DATABASE_URL: "sqlite+aiosqlite:///:memory:"
      run: uv run pytest 